---
title: "Untitled"
author: "Caitie"
date: "2025-10-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(terra)
library(here)
library(tidyverse)
library(sf)
library(ggplot2)
library(tmap)
library(maps)
library(rnaturalearth)
library(countrycode)
```

Area

```{r}
area_df<-read_csv(here("output_data/Paolo_results/Collated/Combined_area_by_country.csv"))
```

```{r}
mpa_df_25<-area_df %>% 
  filter(type == "MPA",
         buff == 25)
```

```{r}

mpa_df_25$name<-countrycode(sourcevar = mpa_df_25$rgn_key, origin = "iso3c", destination = "country.name.en")

eu_mpa<-mpa_df_25 %>%
  filter(!name %in% c("China", "South Korea", "Vietnam", "Taiwan"))

ggplot(eu_mpa, aes(x = reorder(name, prop_int), y = prop_int*100)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  coord_flip() +
  #scale_fill_gradientn(
  #  colours = c("darkgoldenrod1", "darkorange2", "darkred")
  #) +
  labs(x = "Country",
       y = "Offshore wind (25km buffer) and\nmarine protected area overlap (%)",
       fill = expression("MPA area\n(100 thousands km"^2*")"))
```

```{r}
ggsave(here("figures/Europe_MPA_overlap_25_buff.png"), width = 4, height = 3)
```

# Stacked bar
```{r}
mpa_all_25<-area_df %>%
  filter(type %in% c("Non-strict MPA", "Strict MPA", "MPA"),
         buff == 25)

```

```{r}

mpa_all_25$name<-countrycode(sourcevar = mpa_all_25$rgn_key, origin = "iso3c", destination = "country.name.en")

eu_mpa<-mpa_all_25 %>%
  filter(!name %in% c("China", "South Korea", "Vietnam", "Taiwan")) 

test<- eu_mpa %>%
  distinct(prop_int, .keep_all = TRUE) %>% 
  mutate(fill_label = ifelse(type == "Non-strict MPA", "Non-strict",
                             ifelse(type == "Strict MPA", "Strict",
                                    "All")))

#mpa_wide<-pivot_wider(test, names_from = "type", values_from = "prop_int")


ggplot(test, aes(fill = fill_label, x = reorder(name, prop_int), y = prop_int*100)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  coord_flip() +
  scale_fill_manual(values = c("All" = "darkblue", "Strict" = "lightblue", "Non-strict" = "royalblue"))+
  labs(x = "Country",
       y = "Marine protected area extent (%)\noverlapping with offshore wind\ninfrastructure (25 km buffer)",
       fill = "MPA type") +
 theme(legend.position = "none")
```
```{r}
ggsave(here("figures/Europe_MPA_overlap_25_buff_MPAtypes.png"), width = 4, height = 3)
```

```{r}
buff_mpa<-area_df %>%
  filter(type %in% c("MPA"))

buff_mpa$name<-countrycode(sourcevar = buff_mpa$rgn_key, origin = "iso3c", destination = "country.name.en")

eu_buff_mpa<-buff_mpa%>%
  filter(!name %in% c("China", "South Korea", "Vietnam", "Taiwan")) %>% 
  mutate(buff = as.character(buff))

```

```{r}
ggplot(eu_buff_mpa, aes(fill = buff, x = reorder(name, prop_int), y = prop_int*100)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  coord_flip() +
  scale_fill_manual(values = c("25" = "darkblue", "15" = "lightblue", "1" = "royalblue"))+
  labs(x = "Country",
       y = "Marine protected area extent (%)\noverlapping with offshore wind\ninfrastructure (25 km buffer)",
       fill = "Buffer size") +
 theme(legend.position = "none")
```
```{r}
ggsave(here("figures/Europe_MPA_overlap_25_buff_sensitivity.png"), width = 4, height = 3)
```

