---
title: "Untitled"
author: "Caitie"
date: "2026-07-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tmap)
library(sf)
library(dplyr)
library(countrycode)
```


# Wind turbine locations

```{r}
wind_points<-st_read(here("output_data/Paolo_results/Wind_pt_EEZ_intersect.shp"))
```

# Environmentally suitable areas

```{r}
env_suit<-rast(here("raw_data/Wind/wind_pd_mask_NoMPAs.tif"))
env_suit[env_suit>0]<- 1
env_suit[is.na(env_suit)]<-0

env_suit_proj<-project(env_suit, "ESRI:54017")
```

```{r}
env_suit_poly<-as.polygons(env_suit_proj)
env_suit_sf<-st_as_sf(env_suit_poly)
```


# EEZ
```{r}
eez<-st_read(here("raw_data/EEZ/eez_simple.shp")) %>% 
   st_make_valid(.) %>% 
  st_transform(., crs = "ESRI:54017")
```
Intersect EEZ and env suitability

```{r}
eez_env_suit<-st_intersection(env_suit_sf, eez) 

test<-eez_env_suit %>% 
  filter(gwa3_250_powerdensity_100m == 1)
```

# Plot

```{r}
#tmap_mode("plot")

#tm_shape(eez) +
#  tm_polygons(
#    col = "white",
#    border.col = "grey40",
#    lwd = 0.7
#  ) +
 map1<- tm_shape(test) +
  tm_polygons(
    col = "darkgreen",
    alpha = 0.6,
    border.col = NA
  ) +
  tm_shape(wind_points) +
  tm_dots(
    col = "black",
    size = 0.03,
    alpha = 0.8
  ) +
  tm_layout(
    frame = FALSE,
    legend.outside = TRUE,
    main.title.size = 1
  )

map1
```

```{r}
tmap_save(
  map1,
  filename = here("figures/Figure_Supp_suitability_turbine_map.png"),
  width = 8,
  height = 6,
  units = "in"
)
```


```{r}


# Countries to show
plot_countries <- c("DEU", "DNK") # change/add e.g. "BEL", "GBR", "NLD"

eez_plot <- eez %>%
  filter(rgn_key %in% plot_countries)

suit_plot <- eez_env_suit %>%
  filter(rgn_key %in% plot_countries)

wind_plot <- wind_points_proj %>%
  filter(rgn_key %in% plot_countries)

# Nice facet labels
eez_plot <- eez_plot %>%
  mutate(country = countrycode(rgn_key, "iso3c", "country.name"))

suit_plot <- suit_plot %>%
  mutate(country = countrycode(rgn_key, "iso3c", "country.name"))

wind_plot <- wind_plot %>%
  mutate(country = countrycode(rgn_key, "iso3c", "country.name"))

tm_shape(eez_plot) +
  tm_polygons(
    col = "white",
    border.col = "grey40",
    lwd = 0.7
  ) +
  tm_shape(suit_plot) +
  tm_polygons(
    col = "grey70",
    alpha = 0.6,
    border.col = NA
  ) +
  tm_shape(wind_plot) +
  tm_dots(
    col = "black",
    size = 0.03,
    alpha = 0.8
  ) +
  tm_facets(by = "country", free.coords = TRUE, ncol = 2) +
  tm_layout(
    frame = FALSE,
    legend.outside = TRUE,
    main.title = "Environmentally suitable offshore wind areas and turbine locations",
    main.title.size = 1
  )
```


