---
title: "WDPA"
author: "Caitie"
date: "2025-09-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# COUNTRY RESULTS

# Collate results

```{r}
result_files<-list.files(here("output_data/Paolo_results"), full.names = T)
```

# Count data

```{r}
count_results<- result_files[grep("count", result_files)]

total<-read.csv(count_results[[1]]) %>% 
  rename(total_wind = num_wind) %>% 
  select(-X)

count_results2<-count_results[2:10]

count_dfs<-lapply(count_results2, read.csv)

combined_count <- do.call(rbind, count_dfs) %>% 
  rename(overlap_wind = num_wind) %>% 
  select(-X)

combined_count2<-full_join(combined_count, total, by = "rgn_key") %>% 
  mutate(overlap_wind = ifelse(is.na(overlap_wind) == T, 0, overlap_wind)) %>% 
  mutate(prop_count = overlap_wind/total_wind) %>% 
  mutate(type = ifelse(is.na(type) == T, "Non-strict MPA", type))

```

```{r}
write.csv(combined_count2, here("output_data/Paolo_results/Collated/Combined_count_by_country.csv"))
```


# Area data

```{r}
area_results<- result_files[grep("area", result_files)]
area_results<-area_results[grep("Country", area_results, invert = T)]
area_results<-area_results[grep("Collated", area_results, invert = T)]

area_dfs<-lapply(area_results, read.csv)

c_result_files<-result_files[grep("Country", result_files)][[1]]

ow_area<-read.csv(c_result_files)
```

```{r}
combined_area<-c()

# Only do 1:5 as wilderness is messing things up
for(i in 1:length(area_dfs)){
  df<-area_dfs[[i]]
  print(i)
 
   if(unique(df$type) == "Wilderness"){
    df<-df %>%
      mutate(area_km2 = NA)
      colnames(df)[3] <- "feature_km2"
   }else{
  colnames(df)[4] <- "feature_km2"
   }
  combined_area<-rbind(combined_area, df)
  
}
```
```{r}
combined_areaX<-combined_area %>% 
  select(-X) %>% 
  distinct(.)

combined_area2<-full_join(combined_areaX, ow_area, by = c("rgn_key", "buff")) %>% 
  mutate(prop_wind_int= int_km2/iso3_wind_km2) %>% 
  select(-X)

test<-combined_area2 %>% 
  select(rgn_key, buff, iso3_wind_km2) %>% 
  distinct(.)

global<-read_csv(here("output_data/Paolo_results/Global_combined_bio_features_iso3.csv")) %>% 
        rename(feature_km2 = bio_iso3_km2,
         int_km2 = bio_iso3_wind_km2,
         prop_wind_int = prop_int_wind) %>% 
  mutate(type = "All") %>% 
  full_join(test,., by = c("rgn_key", "buff")) %>% 
  select(-`...1`)

combined_area3<-rbind(combined_area2, global) %>% 
  filter(!type == "Natura2000")


write.csv(combined_area3, here("output_data/Paolo_results/Collated/Combined_area_by_country.csv"))
```

```{r}
all<-full_join(combined_area3, total, by = c("rgn_key")) 
all2<-full_join(all, combined_count2, by = c("rgn_key", "type", "total_wind")) %>% 
  mutate(overlap_wind = ifelse(is.na(overlap_wind) == T, 0, overlap_wind),
        prop_count = overlap_wind/total_wind)
```

```{r}
write.csv(all2, here("output_data/Paolo_results/Collated/Final_country_all_results.csv"))
```



# GLOBAL RESULTS

```{r}
global<-read.csv(here("output_data/Paolo_results/Global_combined_bio_features.csv")) %>% 
  mutate(type = "All")

buff1<-global %>% 
  filter(buff == 1)
```

```{r}
global_features<-read.csv(here("output_data/Paolo_results/Collated/Global_bio_feature_results.csv")) %>% 
  select(-diss, -diss.1) 


all_global<-rbind(global, global_features)
```


```{r}
global_total_count<-sum(total$total_wind)

combined_count4<-combined_count %>% 
  group_by(type) %>% 
  summarise(overlap_wind = sum(overlap_wind, na.rm = T)) %>% 
  filter(type != "Natura2000")


global2<-all_global %>% 
  dplyr::mutate(total_count = global_total_count)

global3<-full_join(global2, combined_count4, by = "type") 

```

```{r}

write.csv(global3, here("output_data/Paolo_results/Collated/Global_all_results.csv"))
```



