---
title: "Untitled"
author: "Caitie"
date: "2024-07-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(terra)
library(here)
library(tidyverse)
library(sf)
```

# Load Offshore infrastructure data

Data is from this paper: https://www.nature.com/articles/s41586-023-06825-8


```{r}
dat<-read_csv(here("raw_data/Paolo_offshore_infrastructure/offshore_infrastructure_v20231106.csv"))

offshore_infra<-dat %>% 
  filter(!label == "lake_maracaibo") %>%
  select(lat, lon, label)
```

```{r}
table(dat$label)
```

# This plots points, which may be good enough but should be easy to convert to raster
```{r}#
infra_sf<-infra_sf %>% 
  mutate(label_ID = ifelse(label == "oil", 1,
                           ifelse(label == "possible_oil", 2,
                                  ifelse(label == "probable_oil", 3,
                                         ifelse(label == "wind", 4,
                                                ifelse(label == "possible_wind", 5,
                                                     ifelse(label == "probable_wind", 6,
                                                            ifelse(label == "unknown", 7, 0))))))))

infra_df<-infra_sf %>% 
  as.data.frame(.) %>% 
  select(-geometry) %>% 
  distinct(.) %>% 
  arrange(label_ID)

write.csv(infra_df, here("output_data/offshore_infrastructure/Offshore_infrastructure_key.csv"))


```

```{r}
infra_sf = st_as_sf(offshore_infra, coords = c("lon", "lat"), 
                 crs = 4326) %>% 
  st_transform(., "EPSG:4326")

infra_sf_proj<-sf::st_transform(infra_sf, crs = "ESRI:54017")
```


```{r}
#plot(st_geometry(infra_sf_proj))
```

```{r}
wind<-infra_sf_proj %>%
  filter(label %in% c("probable_wind", "wind"))

wind2 <- wind %>%
  distinct(st_coordinates(.)[, "X"], st_coordinates(.)[, "Y"], .keep_all = TRUE)
```


```{r}
st_write(wind2, here("output_data/offshore_wind/Wind_point_locations.shp"), append = FALSE)
```
# Buffers

25

```{r}
wind_buff25<-st_buffer(wind2, dist = 25000) 

wind_buff25_2<-wind_buff25 %>% 
  mutate(diss = 1) %>%
  group_by(diss) %>% 
  summarise(.) %>% 
  mutate(wind_km2 = as.numeric(st_area(.))*1e-6)

st_write(wind_buff25_2, here("output_data/offshore_wind/Wind_buffer_25km.shp"), append = FALSE)
```

15


```{r}
wind_buff15<-st_buffer(wind2, dist = 15000) 

wind_buff15_2<-wind_buff15 %>% 
  mutate(diss = 1) %>%
  group_by(diss) %>% 
  summarise(.) %>% 
  mutate(wind_km2 = as.numeric(st_area(.))*1e-6)

st_write(wind_buff15_2, here("output_data/offshore_wind/Wind_buffer_15km.shp"), append = FALSE)
```

1


```{r}
wind_buff1<-st_buffer(wind2, dist = 1000) 

wind_buff1_2<-wind_buff1 %>% 
  mutate(diss = 1) %>%
  group_by(diss) %>% 
  summarise(.) %>% 
  mutate(wind_km2 = as.numeric(st_area(.))*1e-6)

st_write(wind_buff1_2, here("output_data/offshore_wind/Wind_buffer_1km.shp"), append = FALSE)
```



