---
title: "Untitled"
author: "Caitie"
date: "2025-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library(terra)
library(sf)
library(tidyverse)
library(here)
library(exactextractr)
```

# EBSAs
https://www.cbd.int/ebsa/repository
```{r}
ebsa<-st_read(here("raw_data/EBSA/Ecologically_or_Biologically_Significant_Marine_Areas_(EBSAs).shp")) %>% 
  st_make_valid(.)

ebsa_ll <- st_transform(ebsa, 4326)
   # st_transform(., crs = "ESRI:54017")
```

```{r}
ebsa_diss<-ebsa%>% 
  mutate(diss = 1) %>%
  group_by(diss) %>% 
  summarise(.) %>% 
  st_transform("ESRI:54017")
```

# EEZ intersect

```{r}
eez<-st_read(here("raw_data/EEZ/eez_simple.shp")) %>% 
   st_make_valid(.) %>% 
  st_transform(., crs = "ESRI:54017")
```

```{r}
eez_ebsa<-st_intersection(eez,ebsa_diss) %>% 
  mutate(ebsa_km2 = as.numeric(st_area(.)*1e-6))

eez_ebsa<-eez_ebsa %>%
  select(rgn_key, area_km2, ebsa_km2)
```

```{r}
test<-eez %>% 
  filter(rgn_key == 'GBR')
```


```{r}
st_write(eez_ebsa, here("output_data/biodiversity_features/EBSA_EEZ_intersect.shp"), append = F)
```

# Infrastructure data
```{r}
wind_points<-st_read(here("output_data/offshore_wind/Wind_point_locations.shp"))
wind25<-st_read(here("output_data/offshore_wind/Wind_buffer_25km.shp"))
wind15<-st_read(here("output_data/offshore_wind/Wind_buffer_15km.shp")) 
wind1<-st_read(here("output_data/offshore_wind/Wind_buffer_1km.shp")) 
```


# Infrastructure intersect

Number of infrastructure
```{r}
ebsa_num_wind<-st_intersection(eez_ebsa, wind_points)

ebsa_wind_count<-ebsa_num_wind %>% 
  distinct(geometry, .keep_all = TRUE) %>% 
  mutate(count = 1) %>%
  group_by(rgn_key) %>% 
  summarise(num_wind = sum(count, na.rm = T)) %>% 
  mutate(type = "EBSA") %>% 
  as.data.frame() %>% 
  select(-geometry)
```

```{r}
write.csv(ebsa_wind_count, here("output_data/Paolo_results/EBSA_wind_count.csv"))
```


Area for buffers

```{r}
ebsa_wind25<-st_intersection(eez_ebsa, wind25) %>% 
  mutate(int_km2 = as.numeric(st_area(.)*1e-6),
         buff = 25) %>% 
  select(-diss)
```

```{r}
ebsa_wind15<-st_intersection(eez_ebsa, wind15) %>% 
  mutate(int_km2 = as.numeric(st_area(.)*1e-6),
         buff = 15) %>% 
  select(-diss)
```

```{r}
ebsa_wind1<-st_intersection(eez_ebsa, wind1) %>% 
  mutate(int_km2 = as.numeric(st_area(.)*1e-6),
         buff = 1) %>% 
  select(-diss)
```

```{r}
all_buff<-rbind(ebsa_wind25, ebsa_wind15, ebsa_wind1) %>% 
  mutate(prop_int = int_km2/ebsa_km2,
         type = "EBSA") %>% 
  as.data.frame() %>% 
  select(-geometry)
```

```{r}
write.csv(all_buff, here("output_data/Paolo_results/EBSA_wind_area.csv"))
```





