---
title: "Marine_wilderness"
author: "Caitie"
date: "2024-07-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library(terra)
library(sf)
library(tidyverse)
library(here)
library(exactextractr)
```

# Offshore infrastructure data

```{r}
infra<-st_read(here("output_data/offshore_infrastructure/Infrastructure_locations.shp")) 
```


```{r}
infra_df<-as.data.frame(table(infra$label)) %>% 
  rename(Type = Var1,
         Total_Infrastructure = Freq)
```


# Marine wilderness data

```{r}
wild<-rast(here("raw_data/marine_wilderness/global_wild.tif"))
#wild[wild==0]<-1
```



# Overlap

```{r}
infra_wild<-terra::extract(wild, infra, method = "simple", cells = TRUE, xy = TRUE, bind = TRUE)

sub_infra_wild<-subset(infra_wild, infra_wild$global_wild == 0)

infra_wild_df<-as.data.frame(table(sub_infra_wild$label)) %>% 
  rename(Type = Var1,
         Infra_wild = Freq)


writeVector(sub_infra_wild, here("output_data/marine_wilderness/Wilderness_infrastructure_overlap.shp"))
```


# Results by EEZ

```{r}
eez<-st_read(here("raw_data/EEZ/eez_simple.shp")) %>% 
  group_by(rgn_key) %>% 
  summarise() %>% 
  st_transform(., crs = "ESRI:54017")

st_write(eez, here("output_data/EEZ/EEZ_diss.shp"))

```

```{r}
infra_eez<-st_intersection(eez, infra)
```

```{r}
infra_eez_wild<-terra::extract(wild, infra_eez, method = "simple", cells = TRUE, xy = TRUE, bind = TRUE)
```

```{r}
sub_infra_eez_wild<-subset(infra_eez_wild, infra_eez_wild$global_wild == 0)

writeVector(sub_infra_eez_wild, here("output_data/marine_wilderness/EEZ_wilderness_infrastructure_overlap.shp"))

infra_eez_wild_df<-as.data.frame(table(sub_infra_eez_wild$label)) %>% 
  rename(Type = Var1,
         EEZ_wild = Freq)

infra_eez_wild_df2<-as.data.frame(table(sub_infra_eez_wild$rgn_key, sub_infra_eez_wild$label)) %>% 
  rename(ISO3 = Var1,
         Type = Var2,
         EEZ_wild = Freq)

write.csv(infra_eez_wild_df2, here("output_data/marine_wilderness/EEZ_wilderness_overlap_results.csv"))
```

# Join results

```{r}
all_results<-full_join(infra_df, infra_wild_df) %>% 
  full_join(., infra_eez_wild_df) %>% 
  mutate(Infra_wild = ifelse(is.na(Infra_wild) == T, 0, Infra_wild),
         EEZ_wild = ifelse(is.na(EEZ_wild) == T, 0, EEZ_wild)) %>% 
  mutate(prop_wild = (Infra_wild/Total_Infrastructure),
         prop_wild_eez = (EEZ_wild/Total_Infrastructure))

write.csv(all_results, here("output_data/marine_wilderness/Wilderness_overlap_results.csv"))
```

