---
title: "Untitled"
author: "Caitie"
date: "2024-07-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(terra)
library(here)
library(tidyverse)
library(sf)
```


```{r}
dat<-read_csv(here("raw_data/offshore_infrastructure_v20231106.csv"))

wind<-dat %>% 
  mutate(wind = ifelse(label %in% c("possible_wind", "probable_wind", "wind"), 1, 0)) %>% 
  select(lat, lon, wind)
```

```{r}
table(dat$label)
table(wind$wind)
```

# This plots points, which may be good enough but should be easy to convert to raster
```{r}
wind_sf = st_as_sf(wind, coords = c("lon", "lat"), 
                 crs = 4326)

wind_sf2<-wind_sf %>% 
  filter(wind == 1)


```

```{r}
plot(st_geometry(wind_sf2))
```
```{r}

```


# Turn sf points into raster

Trying to guess the resolution here - but guesses it is 0 so doesn't work
```{r}
# Convert sf object to spatstat ppp object to calculate nearest neighbor distance
points_ppp <- as.ppp(st_coordinates(wind_sf), W = as.owin(st_bbox(wind_sf)))

# Calculate the average nearest neighbor distance
mean_nnd <- mean(nndist(points_ppp))

# Define the extent of the raster
extent <- ext(st_bbox(wind_sf))

# Create an empty raster with the calculated resolution
r <- rast(extent, res = mean_nnd)

# Rasterize the points using the value field
rasterized <- rasterize(points_sf, r, field = "value")

# Plot the raster to check the result
plot(rasterized)
```


Other tries at making raster, but doesn't work
Says cells aren't regular
```{r}

r <- wind_sf|>
  terra::vect() |>
  terra::rast()

terra::values(r) <- wind_sf$wind
terra::plot(r)

wind2<-wind %>% 
  select(lon, lat, wind) %>% 
  rename(x = lon,
         y = lat,
         z = wind) %>% 
  as.data.frame(.)

wind_ras<-rast(wind2, crs = "EPGS:4326", type="xyz")
```

